sudo: false
cache: bundler
language: ruby
bundler_args: --without development
script: 'bundle exec rake test'
services:
  - mongodb
  - redis-server
rvm:
- 2.2.0
env:
- DB=mongodb
- DB=redis
- DB=active_record
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
before_script:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc' # skip installing docs for gems
matrix:
  exclude:
  allow_failures:
    - rvm: ruby-head
